// <auto-generated />
using System;
using EcomProject.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcomProject.DAL.Migrations
{
    [DbContext(typeof(EcommDBContext))]
    [Migration("20250526002025_Adding_entity_address")]
    partial class Adding_entity_address
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcomProject.DAL.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AddressId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("Addresss");
                });

            modelBuilder.Entity("EcomProject.DAL.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Devices and gadgets for everyday use.",
                            Name = "Electronics"
                        },
                        new
                        {
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Comfortable and stylish furniture for home and office.",
                            Name = "Furniture"
                        },
                        new
                        {
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Smart devices for home management.",
                            Name = "Home Automation"
                        },
                        new
                        {
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "High-quality kitchen and dining products.",
                            Name = "Kitchenware"
                        },
                        new
                        {
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Equipment and accessories for fitness enthusiasts.",
                            Name = "Fitness"
                        },
                        new
                        {
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "High-quality audio devices for music lovers.",
                            Name = "Audio"
                        },
                        new
                        {
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Description = "Essential home appliances for daily use.",
                            Name = "Appliances"
                        },
                        new
                        {
                            CategoryId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Description = "Modern lighting solutions for home and office.",
                            Name = "Lighting"
                        },
                        new
                        {
                            CategoryId = new Guid("99999999-9999-9999-9999-999999999999"),
                            Description = "Durable and stylish bags for travel and daily use.",
                            Name = "Bags & Luggage"
                        },
                        new
                        {
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Accessories to enhance your computing experience.",
                            Name = "Computer Accessories"
                        });
                });

            modelBuilder.Entity("EcomProject.DAL.Models.Photo", b =>
                {
                    b.Property<Guid>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhotoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PhotoId");

                    b.HasIndex("ProductId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("EcomProject.DAL.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ManufactureDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Noise-cancelling wireless headphones with 20-hour battery life.",
                            Discount = 10,
                            ManufactureDate = new DateOnly(2023, 1, 15),
                            Name = "Wireless Headphones",
                            Price = 199.99m
                        },
                        new
                        {
                            ProductId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Ergonomic leather chair for office use.",
                            Discount = 15,
                            ManufactureDate = new DateOnly(2022, 11, 20),
                            Name = "Leather Office Chair",
                            Price = 299.99m
                        },
                        new
                        {
                            ProductId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Wi-Fi enabled thermostat for energy-efficient heating.",
                            Discount = 5,
                            ManufactureDate = new DateOnly(2023, 3, 5),
                            Name = "Smart Thermostat",
                            Price = 149.99m
                        },
                        new
                        {
                            ProductId = new Guid("b4444444-4444-4444-4444-444444444444"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Insulated stainless steel water bottle, 1L capacity.",
                            Discount = 0,
                            ManufactureDate = new DateOnly(2023, 2, 10),
                            Name = "Stainless Steel Water Bottle",
                            Price = 24.99m
                        },
                        new
                        {
                            ProductId = new Guid("b5555555-5555-5555-5555-555555555555"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Eco-friendly yoga mat with non-slip surface.",
                            Discount = 20,
                            ManufactureDate = new DateOnly(2023, 4, 1),
                            Name = "Yoga Mat",
                            Price = 39.99m
                        },
                        new
                        {
                            ProductId = new Guid("b6666666-6666-6666-6666-666666666666"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Portable Bluetooth speaker with 12-hour battery life.",
                            Discount = 10,
                            ManufactureDate = new DateOnly(2023, 1, 25),
                            Name = "Bluetooth Speaker",
                            Price = 79.99m
                        },
                        new
                        {
                            ProductId = new Guid("b7777777-7777-7777-7777-777777777777"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Description = "Fast-boiling electric kettle with auto-shutoff.",
                            Discount = 0,
                            ManufactureDate = new DateOnly(2023, 3, 15),
                            Name = "Electric Kettle",
                            Price = 49.99m
                        },
                        new
                        {
                            ProductId = new Guid("b8888888-8888-8888-8888-888888888888"),
                            CategoryId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Description = "Adjustable LED desk lamp with 3 brightness levels.",
                            Discount = 5,
                            ManufactureDate = new DateOnly(2023, 2, 28),
                            Name = "LED Desk Lamp",
                            Price = 34.99m
                        },
                        new
                        {
                            ProductId = new Guid("b9999999-9999-9999-9999-999999999999"),
                            CategoryId = new Guid("99999999-9999-9999-9999-999999999999"),
                            Description = "Water-resistant backpack with multiple compartments.",
                            Discount = 15,
                            ManufactureDate = new DateOnly(2023, 4, 10),
                            Name = "Backpack",
                            Price = 59.99m
                        },
                        new
                        {
                            ProductId = new Guid("baaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Ergonomic wireless mouse with silent clicks.",
                            Discount = 0,
                            ManufactureDate = new DateOnly(2023, 3, 20),
                            Name = "Wireless Mouse",
                            Price = 29.99m
                        });
                });

            modelBuilder.Entity("EcomProject.DAL.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("EcomProject.DAL.Models.Address", b =>
                {
                    b.HasOne("EcomProject.DAL.Models.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("EcomProject.DAL.Models.Address", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcomProject.DAL.Models.Photo", b =>
                {
                    b.HasOne("EcomProject.DAL.Models.Product", "Product")
                        .WithMany("Photos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EcomProject.DAL.Models.Product", b =>
                {
                    b.HasOne("EcomProject.DAL.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("EcomProject.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("EcomProject.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcomProject.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("EcomProject.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcomProject.DAL.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EcomProject.DAL.Models.Product", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("EcomProject.DAL.Models.User", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
